resource "aws_secretsmanager_secret" "this" {
  # Fill in the name you gave to your secret
  name        = "${var.service_name}-tf"
  description = "Generated by Terraform for ${var.service_name}"

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "this" {
  secret_id     = aws_secretsmanager_secret.this.id
  secret_string = jsonencode(local.secrets)
}

locals {
  secrets = merge(
    var.secrets,
    {
      next_sls_cognito_identity_pool_id    = "${var.cognito_identity_pool_id}"
      next_sls_cognito_user_pool_id        = "${var.cognito_user_pool_id}"
      next_sls_cognito_user_pool_client_id = "${var.cognito_user_pool_client_id}"
      sls_cognito_authorizer               = "${var.cognito_authorizer}"
      sls_cognito_user_pool_client_arn     = "${var.cognito_user_pool_client_arn}"
      sls_api_gateway_root_resource_id     = "${var.api_gateway_root_resource_id}"
      sls_api_gateway_rest_api_id          = "${var.api_gateway_rest_api_id}"
      sls_user_table_id                    = "${var.user_table_id}"
      sls_positions_table_id               = "${var.positions_table_id}"
    },
  )
}
